# Generated by Django 3.1.2 on 2020-10-21 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True, verbose_name='Идентификатор пользователя')),
            ],
        ),
        migrations.CreateModel(
            name='SearchArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True, verbose_name='Область')),
            ],
        ),
        migrations.CreateModel(
            name='ResultSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255, verbose_name='Запрос')),
                ('result', models.TextField(verbose_name='Результат запроса')),
                ('query_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата запроса')),
                ('bot_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_service_api.botuser')),
            ],
        ),
    ]
