# Generated by Django 3.1.2 on 2020-10-21 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_service_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Никнейм пользователя'),
        ),
    ]
