# Generated by Django 3.1.2 on 2020-10-21 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search_service_api', '0002_botuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultsearch',
            name='bot_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='search_service_api.botuser'),
        ),
    ]
