# Generated by Django 3.1.2 on 2020-10-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_service_api', '0003_auto_20201021_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botuser',
            name='id',
        ),
        migrations.AlterField(
            model_name='botuser',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Идентификатор пользователя telegram'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Юзернейм пользователя'),
        ),
    ]
